<?php

namespace PaneeDesign\StorageBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
}
